name: Validate on PR Approval

on:
  push:
    branches-ignore:
            - master
        paths:
            - 'force-app/**'

jobs:
    validate-branch-name:
        runs-on: ubuntu-latest
        steps:
            - name: Validate branch name requirements
              uses: NareshSFDC1995/CICD-test@master
              with:
                  regex: '([a-z])+\/([a-z])+'
                  min_length: 6